apiVersion: v1
kind: Secret
metadata:
  name: security-patrol-secrets
  namespace: security-patrol
type: Opaque
data:
  # Base64 encoded values
  # SA_PASSWORD: SecPatrol@Sql2024!
  SA_PASSWORD: U2VjUGF0cm9sQFNxbDIwMjQh
  # Connection string (base64 encoded)
  # Server=sqlserver;Database=SecurityPatrol;User Id=sa;Password=SecPatrol@Sql2024!;TrustServerCertificate=True;
  connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1TZWN1cml0eVBhdHJvbDtVc2VyIElkPXNhO1Bhc3N3b3JkPVNlY1BhdHJvbEBTcWwyMDI0ITtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7
